### ISSUE TITLE
No notifications on my iPhone

### ISSUE THREAD

**Issue by shantamg** [EddyVerbruggen/nativescript-local-notifications#1]
Works great on android and ios emulators, but when I deploy to my actual iphone no notifications are happening. I can see in the xcode console that the events are firing, but I don't see any notification on the device. Any clues? What could be different?

**Comment by shantamg** [comment]
Hmm... when the app is in the background and a notification is supposed to happen, it doesn't, but as soon as I open the app, it fires. Then, when I go back to the home screen, I see the badges, but the notifications are not in the notification center...

Seems like the js is not firing when the app is in the background, but only on my device... works fine on the emulator.

**Comment by EddyVerbruggen** [comment]
Are you using the [demo app](https://github.com/EddyVerbruggen/nativescript-local-notifications-demo) or your own? I've just reconfirmed all these usecases work fine on my 6s. Using `tns --version` 1.5.2.

And by 'it fires' when opening the app you mean the listener fires, not the actual notification, right? That's expected afaik.

**Comment by shantamg** [comment]
What I was seeing happen seems not to have to do with nativescript-local-notifications after all. I believe this plugin is functioning as designed, but my use case was strange (involving PubNub).

As it turns out (see [NativeScript issue #1403](https://github.com/NativeScript/NativeScript/issues/1403)), js execution cannot be guaranteed when the app is running in the background. For me that means that messages that come from an outside source (like PubNub) won't trigger a notification if the app is in the background and the js has stopped.

Scheduled notifications work fine because they (correct me if I'm wrong) are scheduled via js when the app is running but are handled by the os (not a js timer).
