### ISSUE TITLE
Doesn't work if too many notifications?

### ISSUE THREAD

**Issue by NL33** [EddyVerbruggen/nativescript-local-notifications#102]
I have found in testing that scheduling the notifications sometimes works and sometimes does not.  I have not been able to determine why this might be the case. 

One possibility: if too many notifications are scheduled, it overloads the phone's resources, and nothing happens. So that I can schedule notifications without issue up to a certain amount of notifications, and after that amount it won't work. Is that possible? Are there other instances where people have found the behavior to be inconsistent? (meaning same code, but sometimes works and sometimes does not)

In my case, I want the user to be able to choose to schedule notifications and how many. So I run a loop for the number of times the user selects, like so:
```
   for (var i = 1; i <= number_of_times_user_selects; i++) {
        LocalNotifications.schedule([{
          id: id,
          title: 'Titletext',
          body: 'bodytext,
          at: setTime //setTime here is a time that changes for each iteration of the loop based on user selection. Each iteration of the loop will be for a later time.
        }])
      }
```

Is it possible that if the 'number_of_times_user_selects' is too high, the functionality just shuts down? I don't know what the limit would be, but it seems like the breakdown happens when the number of times reaches at least 30, 40, etc... 

This is on iOS. Console messages for when the notifications show up and when they don't seem to be the same. So the only difference I can tell is the number of notifications scheduled to be shown.

Even there it is inconsistent--as sometimes the same amount of notifications works, sometimes it doesn't, and sometimes there is an odd behavior where no notifications are shown until the end of the loop, and they are all shown together.

Any ideas?

Here is an example output:
```
<UIUserNotificationSettings: 0x170631120; types: (none);>
<UIUserNotificationSettings: 0x170631ee0; types: (none);>
<UIUserNotificationSettings: 0x17442b3a0; types: (none);>
<UIUserNotificationSettings: 0x17442b5a0; types: (none);>
<UIUserNotificationSettings: 0x174429060; types: (UIUserNotificationTypeAlert UIUserNotificationTypeBadge UIUserNotificationTypeSound);>
<UIUserNotificationSettings: 0x170629400; types: (UIUserNotificationTypeAlert UIUserNotificationTypeBadge UIUserNotificationTypeSound);>
<UIUserNotificationSettings: 0x17442e080; types: (UIUserNotificationTypeAlert UIUserNotificationTypeBadge UIUserNotificationTypeSound);>
<UIUserNotificationSettings: 0x1744397a0; types: (UIUserNotificationTypeAlert UIUserNotificationTypeBadge UIUserNotificationTypeSound);>
app will resign active
app will suspend
Cannot snapshot view (<UIKeyboardImpl: 0x15d2d1280; frame = (0 0; 320 253); layer = <CALayer: 0x170636f00>>) with afterScreenUpdates:NO, because the view is not in a window. Use afterScreenUpdates:YES.  //NOTE: this is likely from when I close the app on the phone.
TIC TCP Conn Event [4:0x17038b870]: 1073741833 Err(0)
TIC TCP Conn Event [3:0x17038d8f0]: 1073741833 Err(0)
```

**Comment by NL33** [comment]
Quick update: I added some error catching:
```
for (var i = 1; i <= number_of_times_user_selects; i++) {
        LocalNotifications.schedule([{
          id: id,
          title: 'Titletext',
          body: 'bodytext,
          at: setTime //setTime here is a time that changes for each iteration of the loop based on user selection. Each iteration of the loop will be for a later time.
        }])
      }.then(
      function() {
        console.log("Notification scheduled");
      },
      function(error) {
        console.log("scheduling error: " + error);
      }
    )
}
```

The behavior continues to be odd. Most recently I have been scheduling notifications, and the log is properly showing "Notification scheduled" for the notifications. However, only the first (of, say, 5) ends up being shown. So likely the problem is not that I am scheduling too many notifications, but something else.

**Comment by EddyVerbruggen** [comment]
You should not schedule items in a loop as the operation is asynchronous (that's why the function returns a Promise). The nice thing about the `schedule` function is it actually takes an array of notifications so you don't need to wait for the Promise to resolve and call it again.

Hope that makes sense (and actually helps)..

**Comment by NL33** [comment]
That is really helpful to hear. Thanks, Eddy. That saves me a lot of time fiddling around the edges with an approach (the loop) that does not work.

I do remain unsure of one thing, though: how do you set up an array of notifications **within** the schedule function if you don't know how many there will be?(because the user has the choice of how many to schedule). In the circumstance of a user making a choice about the number of something, I always assume the loop is the way to go, but not sure how that works within the schedule function.

**Comment by EddyVerbruggen** [comment]
Exactly 😎☝🏻🤝

**Comment by NL33** [comment]
Thanks, Eddy. It seems to be working now.

**Comment by NL33** [comment]
Since upgrading to version 3.0 this is no longer working for me. Goal is to have the same notification show at different times, as set by user.  

After upgrade, if I create an array of several notifications, and use the code loop structure above, only the final notification now shows. Previously, with same code before upgrade, it worked.

Only change to code is that:
instead of: `import * as LocalNotifications from "nativescript-local-notifications";`
I now have to have the following to avoid errors:
```
require("nativescript-local-notifications");
import { LocalNotifications } from "nativescript-local-notifications";
```
Is there some reason this would no longer work?

**Comment by EddyVerbruggen** [comment]
Is that an issue on both platforms?

**Comment by NL33** [comment]
Just iOS. Haven't tried android.

**Comment by EddyVerbruggen** [comment]
I'm actually creating notifications in a look with the latest version on iOS and have no issues. This is the meat of my code (simplified):

```typescript
import * as LocalNotifications from "nativescript-local-notifications";

[my source array].forEach(notificationData => {
      LocalNotifications.schedule([{
        notificationData.id,
        at: new Date(new Date().getTime() + (1000 * 5) * (1 + Math.random())), // for testing purposes
        badge: 1,
        title: "the title",
        body: "the body"
      }]);
}
```

**Comment by NL33** [comment]
Thanks. I'll take a look.

**Comment by NL33** [comment]
One note: I see that you use the formulation: "import * as LocalNotifications from "nativescript-local-notifications". This is what i used before the upgrade. After the upgrade, code like "LocalNotifications.schedule..." gives error: "Property 'schedule' does not exist on typeOf import(.../...nativescript-local-notifications/index"). Maybe this has something to do with it.

If I change "import * as LocalNotifications from 
`"nativescript-local-notifications"` to 
`"import { LocalNotifications } from "nativescript-local-notifications" `
 I no longer get an error, but I am not able to get the loop to work that was working before. I will look into your code here.

**Comment by NL33** [comment]
Your code works for me, but my previous code does not. I think the issue is that in my code, I was giving each notification in the array the same id. This used to work, but looks like in the new upgrade each notification that is added to the loop has to have a different id.
