### ISSUE TITLE
Android notification image looks pixelated

### ISSUE THREAD

**Issue by Danziger** [EddyVerbruggen/nativescript-local-notifications#111]
The problem is that when the image is loaded, it is resized, I assume to avoid an error due to the `Intent` created in `NotificationRestoreReceiver.java` being too big (`TransactionTooLargeException` / `!!! FAILED BINDER TRANSACTION !!!` exception/error).

To fix this, the image cropping should be removed and the notification probably should not be created until it's going to be displayed. If it's going to be scheduled, then the intent should only contain the `JSON` of the options, which we would later use to create when it's time to display it.

This would simplify the cancellation as well.

Working on the fix.

**Comment by EddyVerbruggen** [comment]
Indeed, the image is resized to avoid that error, but I didn't think it was resized too aggressively to become pixelated. Can you show an example of how bad it becomes, along ith the original image source?

**Comment by Danziger** [comment]
Not pixelated:
![notification image not pixelated](https://user-images.githubusercontent.com/6564894/45218419-d7868500-b2a7-11e8-98a3-e77ea5a572d5.jpg)

Pixelated:
![notification image pixelated](https://user-images.githubusercontent.com/6564894/45218420-d7868500-b2a7-11e8-941b-9266f624687e.jpg)

Original source: https://icdn-0.motor1.com/images/mgl/7WjgW/s3/1974-lancia-stratos-hf-stradale-for-sale.jpg

**Comment by EddyVerbruggen** [comment]
Cool, thanks! It says "Hello iOS!" but it's actually shown on Android, right? Perhaps your testdevice has a much higher resolution (or is a tablet).

**Comment by Danziger** [comment]
@EddyVerbruggen Can you please review this PR? Once it's merged in my fork I will open a PR here: https://github.com/Danziger/nativescript-local-notifications/pull/5 I think that also addressed #113
