### ISSUE TITLE
Can't set priority for Android heads-up notification

### ISSUE THREAD

**Issue by rchisholm** [EddyVerbruggen/nativescript-local-notifications#114]
Hello,

Thank you so much for this plugin. It is has been very helpful for my app's purposes, where push notifications would have been overkill.

However, I find that I am unable to create heads-up notifications. There is no "priority" property, as referenced in issue #98, and I see that heads-up notifications are referenced in issue #69, however this issue recommends using the property "forceShowWhenInForeground" to true, which does not create a heads-up notification (though it does create a regular notification while the app is in the foreground).

Any help would be greatly appreciated. Thanks again!

**Comment by EddyVerbruggen** [comment]
Can you educate me on what a 'heads-up' notification is, and how it's different from one that shows in the foreground (because that's what I thought was meant).

**Comment by rchisholm** [comment]
From [developer.android.com](https://developer.android.com/guide/topics/ui/notifiers/notifications)

Heads-up notification
Beginning with Android 5.0, notifications can briefly appear in a floating window called a heads-up notification. This behavior is normally for important notifications that the user should know about immediately, and it appears only if the device is unlocked.


![heads-up_2x](https://user-images.githubusercontent.com/42742932/45373814-59cfbb80-b5be-11e8-9b79-b4cee9008d7f.png)

Figure 3. A heads-up notification appears in front of the foreground app

The heads-up notification appears the moment your app issues the notification and it disappears after a moment, but remains visible in the notification drawer as usual.


For me, when using the option "forceShowWhenInForeground," the notification displays in the standard notification drawer _while the app is in the foreground_, but doesn't show _the notification in the foreground_, if that makes any sense. The heads-up notification needs to show as a floating window with text (like the default notifications in iOS), not just an icon in the notification drawer, which then shows the notification text and icon when dragged down (like default notifications in Android).

**Comment by Lehren** [comment]
Any update? Would be useful to have this available.

**Comment by EddyVerbruggen** [comment]
@Lehren The main problem is that I'm not entirely sure about the implementation. Would it suffice to expose a `priority` property which takes a number and is passed to [this line](https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/004ccd69f89de7123d4b1b7663b5c1282f212cb9/native-src/android/app/src/main/java/com/telerik/localnotifications/Builder.java#L71)?

**Comment by Lehren** [comment]
@EddyVerbruggen 
For me that would be fine if possible.

**Comment by EddyVerbruggen** [comment]
Alright, available now in 4.1.2. See the readme (look for `priority`).
