### ISSUE TITLE
Version 3.0 Not Showing Notifications if app in foreground

### ISSUE THREAD

**Issue by NL33** [EddyVerbruggen/nativescript-local-notifications#117]
Is version 3.0 meant to show the notification in the foreground? I believe the change-log says it does, but I am not able to get that to work.

On iOS.  Removed old plugin version, cleaned out iOS platform, then added new version of plugin.

Example:
component.ts
```
require("nativescript-local-notifications");
import { LocalNotifications } from "nativescript-local-notifications";  /*btw, I used to use 'import * as LocalNotifications from "nativescript-local-notifications" but that does not work anymore for some reason*/
... 
LocalNotifications.schedule([{
        id: 1,
        title: 'title',
        body: 'this should be the body',
        at: new Date(new Date().getTime() + (10 * 1000)) // 10 seconds from 
    }])
```

This works if I put the app in the background, but not if the app is in the foreground. It does seem like I can hear the notification if the app is in the foreground, but I cannot see the notification.

**Comment by EddyVerbruggen** [comment]
It’s in the F manual: forceShowWhenInForeground

**Comment by NL33** [comment]
Thanks very much! Sorry to miss that. It does seem to work now.

On another previous issue--adding an array of notifications (so that one notification could show up at an interval set by user)--prior working code no longer works after upgrade. I have added a comment to that issue [https://github.com/EddyVerbruggen/nativescript-local-notifications/issues/102(here).
