### ISSUE TITLE
Click in Notification don't call onActivityCreated (android)

### ISSUE THREAD

**Issue by toniclecb** [EddyVerbruggen/nativescript-local-notifications#12]
Everything works fine. Thanks for this plugin.

But, I am facing a problem.
When the app is closed and the user touch the notification the app opens, but the function onActivityCreated is not called.
`application.android.onActivityCreated = function(activity) {...}`
Another functions like onActivityStarted are called normally.

Is this an error? Is this the default behaviour? Can I be doing something wrong?

**Comment by EddyVerbruggen** [comment]
I'm not entirely sure, but since version 3.0.0 is a major refactor I think this has been fixed.
