### ISSUE TITLE
Error LocalNotifications.requestPermission is not a function

### ISSUE THREAD

**Issue by chrisbekas** [EddyVerbruggen/nativescript-local-notifications#123]
Getting this error with the current version 3.1.0

JS ERROR TypeError: LocalNotifications.requestPermission is not a function. (In 'LocalNotifications.requestPermission()', 'LocalNotifications.requestPermission' is undefined)

Updating the [demo app](https://github.com/EddyVerbruggen/nativescript-local-notifications-demo) to this version of the plugin also produces this error.

Using {N} 4.2.0 but also fails with {N} 5.0.

**Comment by EddyVerbruggen** [comment]
How do you run it from the command line?

**Comment by chrisbekas** [comment]
I just run it from within Code using the Nativescript plugin but I've also tried with `tns run ios` both producing this error. Using this plugin in a vanilla JS project. Thanks Eddy!

**Comment by robtoll** [comment]
Hello - I had the same issue. It turns out that when you use vanilla JS, you have to do this...

LocalNotifications = require("nativescript-local-notifications").LocalNotifications;

That should solve your problem

**Comment by pollyolly** [comment]
> Hello - I had the same issue. It turns out that when you use vanilla JS, you have to do this...
> 
> LocalNotifications = require("nativescript-local-notifications").LocalNotifications;
> 
> That should solve your problem

tns platform clean android - failed
tns update - failed
import from - failed
import as from - failed
your solution - works

It works thanks using  Nativescript Vue 2.0 and platform Android 5.0
