### ISSUE TITLE
Android Led notification not working

### ISSUE THREAD

**Issue by jbarnabe** [EddyVerbruggen/nativescript-local-notifications#128]
Hi,

The notifications generated by the plugin does not activate the notification led on Android. Is it possible to add this feature (possibly with the possibility to configure the color of the led) ?

Thx

**Comment by Dreaming-In-Code** [comment]
+1
I too would like the LED functionality to be available in this plugin.

**Comment by htbkoo** [comment]
May I ask if anyone has already picked this up? :-)
If not I would like to try to help and create a PR so people can review it.

**Comment by EddyVerbruggen** [comment]
Not that I’m aware of. Would be happy to test a PR though!

**Comment by htbkoo** [comment]
I had created something like this: #133 but I think it would [require some discussions and updates first](https://github.com/EddyVerbruggen/nativescript-local-notifications/pull/133#issue-245803964).

**Comment by jbarnabe** [comment]
The following here: [#133](https://github.com/EddyVerbruggen/nativescript-local-notifications/pull/133)
