### ISSUE TITLE
No notification sound on ios 

### ISSUE THREAD

**Issue by Obsessive** [EddyVerbruggen/nativescript-local-notifications#13]
No notification sound on ios. 
we get notifications but not the sound. 

core modules @ 2.2.0
ios runtime @ 2.2.0

**Comment by EddyVerbruggen** [comment]
Thanks for reminding me I did not implement it yet - you can now pass in `sound: null` for no sound, or leave it out for the default sound.

**Comment by Obsessive** [comment]
Tested on iOS simulator (tested for sound functionality on other apps first to ensure no issues with simulator sounds)

Steps: 
tns platform remove ios
tns plugin remove nativescript-local-notifications
tns plugin add nativescript-local-notifications
tns platform add ios
tns prepare ios
tns run ios

Result: 
No sound when local notification is received

**Comment by Obsessive** [comment]
will test  on device and report in a while
