### ISSUE TITLE
IOS notifications not working

### ISSUE THREAD

**Issue by codingsett** [EddyVerbruggen/nativescript-local-notifications#130]
Hello i have a small issue, notifications on android work perfectly but on ios no notification appears on the phone or simulator but i got the prompt to allow notifications after installing the app.
I am using pusher to send the notifications.What could be the issue ?

Latest version of nativescript and nativescript sidekick.

```javascript
var pusher = new Pusher('xxxxxxxxxxxxxx', {
    cluster: 'eu',
    forceTLS: true
});

var channel = pusher.subscribe('my-channel');
channel.bind('my-event', function (data) {
    signal=data;
    console.log(signal);
  
    localnotify.requestPermission().then(
        function (granted) {
            console.log("Permission granted? " + granted);
        }
    )
    

    localnotify.schedule([{
        id: 1,
        title: 'Signals',
        body: signal.message,
        channel: 'My Channel', 
        
        at: new Date(new Date().getTime() + (30000)) 
    }]).then(
        function () {
            console.log("Notification scheduled");
        },
        function (error) {
            console.log("scheduling error: " + error);
        }
    )
    localnotify.addOnMessageReceivedCallback(
        function (notification) {
            console.log("ID: " + notification.id);
            console.log("Title: " + notification.title);
            console.log("Body: " + notification.body);
        }
    ).then(
        function () {
            console.log("Listener added");
        }
    )

});


```

![console](https://user-images.githubusercontent.com/27306293/50606836-2a7bec00-0ed8-11e9-8adc-0ba13a220bb6.png)

**Comment by EddyVerbruggen** [comment]
What does Pusher have to do with the actual issue? If you remove that and just schedule the notification, does it work?

**Comment by codingsett** [comment]
when i remove pusher i still don't get notification

**Comment by EddyVerbruggen** [comment]
OK, can you either try the demo in this repo, or share a repo (without Pusher) that shows the problem?

**Comment by codingsett** [comment]
I ran the demo and it worked perfectly and also when i run the code without pusher on my iphone it works but when i use pusher it doesnt. On android with pusher it works perfectly. Any suggestions?

**Comment by EddyVerbruggen** [comment]
In your previous message, you said "when i remove pusher i still don't get notification", but you got it working now?

I have no idea what Pusher is and why that would mess up the plugin. Can't really help you there.
