### ISSUE TITLE
Service exited due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by pn222ez** [EddyVerbruggen/nativescript-local-notifications#14]
When I run schedule in iOS Simulator v.9.2, the app crashes with error "Service exited due to signal: Segmentation fault: 11".

**Comment by EddyVerbruggen** [comment]
That can be caused by many things..

**Comment by pn222ez** [comment]
Ok. I cloned the demo app and every time the schedule method is used it crashes.

**Comment by pn222ez** [comment]
Worked when I had a value for interval.

**Comment by EddyVerbruggen** [comment]
Thanks, fixed in 1.1.2
