### ISSUE TITLE
Failed to verify bitcode in LocalNotificationsPlugin.framework/LocalNotificationsPlugin:

### ISSUE THREAD

**Issue by AquilesOliveira** [EddyVerbruggen/nativescript-local-notifications#145]
Failed to verify bitcode in LocalNotificationsPlugin.framework/LocalNotificationsPlugin:
error: Bundle only contains bitcode-marker /var/folders/4d/zcq9x1910f9_7vk9_v8q6xp8jqxkx7/T/IDEDistributionOptionThinning.~~~119PP8/Payload/cyclist.app/Frameworks/LocalNotificationsPlugin.framework/LocalNotificationsPlugin (armv7)

My environment:
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 10.2.0 satisfies minimum required version 9.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.2 version and is up to date.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.1 version and is up to date.
✔ Component tns-ios has 5.3.1 version and is up to date.

**Comment by dropclick** [comment]
@AquilesOliveira I have the same problem. May I ask how you solved this?
