### ISSUE TITLE
Start to end Date

### ISSUE THREAD

**Issue by nisha-ann** [EddyVerbruggen/nativescript-local-notifications#146]
Hi Eddy,

Can we set a start date to an end date to schedule our local notifications?

**Comment by EddyVerbruggen** [comment]
Please elaborate.

**Comment by nisha-ann** [comment]
Like ,can I give a notification start date to notification end date and they have to be fired at a particular time say 10 am from the start date to end date.

**Comment by EddyVerbruggen** [comment]
There's no such thing as an enddate in this plugin, but either:

- Create a notification to fire at 10am and set `interval` to `day` and cancel it at some point in the future, or
- Create notifications in a loop. Schedule the first one at 10am, the next one at 10am+1 day, until you're at the end date.

**Comment by nisha-ann** [comment]
Ok..This was what I thought of. Was just wondering if it had this feature....just to avoid a loop
