### ISSUE TITLE
A reminder to set every 2 mins

### ISSUE THREAD

**Issue by nisha-ann** [EddyVerbruggen/nativescript-local-notifications#147]
Hi Eddy,
I have a requirement to fire a notification about attending an event. When the user attends the event, it is updated in the server. If the user fails to attend, he has to be forced to attend it by setting reminders for every 2 minutes. How can I implement this?

Should I use a local notification or calendar plugin? Or something else?

**Comment by EddyVerbruggen** [comment]
Sorry, but I need to focus and this is not an issue with the plugin, so closing. Please ask questions like these on Slack or SO.

**Comment by nisha-ann** [comment]
Can you share you slack email I'd..

**Comment by EddyVerbruggen** [comment]
I meant: ask in a channel of the NativeScript Slack. Not DM.

**Comment by nisha-ann** [comment]
I got a solution..for this...and to set reminders with snooze functionality..thanks eddy
