### ISSUE TITLE
ReferenceError: Can't find variable: Notification (iOS 9.3, NS 5.4.1, Angular 8.0.0)

### ISSUE THREAD

**Issue by jpierront** [EddyVerbruggen/nativescript-local-notifications#156]
The error "ReferenceError: Can't find variable: Notification" occurs on my project and on an empty SideKick project.

It fail only on iOS 9.X.

Any idea ?

{
  "nativescript": {
    "id": "org.nativescript.Debug",
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "nativescript-angular": "~8.0.0",
    "nativescript-local-notifications": "^3.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~6.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~5.4.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-sass": "~1.7.0",
    "nativescript-dev-typescript": "~0.10.0",
    "nativescript-dev-webpack": "~0.24.0",
    "tslint": "~5.11.0"
  },
  "gitHead": "8ab7726d1ee9991706069c1359c552e67ee0d1a4",
  "readme": "NativeScript Application"
}

**Comment by markoImake** [comment]
I'm having the same issue when running on devices with iOS 9.X. It's crashing on line 21 of local-notifications.ios.js.

**Comment by EddyVerbruggen** [comment]
That line tries to instantiate a new instance of [this class](https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/master/src/platforms/ios/LocalNotificationsPlugin.framework/Headers/Notification.h) which I guess is not part of your project for some reason. Did you remove your platforms/ios folder after installing the plugin?

I'm not a SideKick user, so not sure if/how that interferes.

**Comment by jpierront** [comment]
It crash even after a rm -rf platforms/ node_modules/ hooks/

I'm talking about a sidekick project only to say that it crash with a "blank" project and not just on my app (which doesn't use SideKick)

**Comment by EddyVerbruggen** [comment]
Hmm.. does it work on a simulator?

**Comment by jpierront** [comment]
I only tested on a simulator, I do not have a real device under iOS 9.X

**Comment by EddyVerbruggen** [comment]
And is it also an issue on newer iOS versions? I don't have an iOS 9 sim/device at all..

**Comment by jpierront** [comment]
iOS 9.X seems to use another notification system. So, iOS 10+ works.

src/local-notifications.ios.ts

```
constructor() {
  super();
  if (LocalNotificationsImpl.isUNUserNotificationCenterAvailable()) {
    // iOS 10+ (I suppose)
    ...
  } else {
    // Before iOS 10 (I suppose)
    ....
    this.notificationHandler = Notification.new(); // ===> It crash
    this.notificationManager = NotificationManager.new();
  }
}
```

**Comment by EddyVerbruggen** [comment]
Isn't that pseudo code the other way around?

Anyway, I don't have an iOS 9 device and its market share is almost 0 so I'm not sure I'll be doing the legwork to support it going forward. I don't mind merging a PR of course.

**Comment by markoImake** [comment]
I did a bit more digging. I'm using the plugin in my production nativescript (plain javascript flavour) app which supports ios9, and I have an ios9 test device (iPhone 4s).
The local notification functionality was working in a previous version of my app and has stopped working now - I get the same "ReferenceError: Can't find variable: Notification" crash upon starting the app. 
I rolled back to a previous version of my app and found that it was working using nativescript 4.2. I then updated that project to the latest version of nativescript (5.4.0) and the crash started happening.
I checked the xCode project for both the newer and older app version and the framework is present and get's linked in the same way. 
@EddyVerbruggen any clue why the newer nativescript version will handle the framework differently?

**Comment by markoImake** [comment]
Narrowed it down a bit more, it works on nativescript 5.2.0, starts breaking on nativescript 5.3.0.

**Comment by markoImake** [comment]
Actually found that the problem is introduced in the nativescript ios-runtime v5.3.0 release. If I build my project with tns-ios version 5.2.0 and tns-core-modules 5.4.3 there are no issues. Using any ios-runtime version >= 5.3.0 results in crash. 
I had a look at the [changelog](https://github.com/NativeScript/ios-runtime/blob/master/CHANGELOG.md#530-2019-03-27) but couldn't spot anything obvious. @EddyVerbruggen any thoughts?

**Comment by EddyVerbruggen** [comment]
I have no clue. If you have a repo I can look at, and instructions to reproduce it, then I'd be happy to take a look. But if it's an iOS9-specific issue then I don't think I'll be able to fix it because I don't have a test device for it, and iOS13 is just around the corner anyway.
