### ISSUE TITLE
System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/NotificationCompat$Builder;

### ISSUE THREAD

**Issue by jasenkabalac** [EddyVerbruggen/nativescript-local-notifications#160]
After clicking the schedule button and then ok, thanks happens this:
System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/NotificationCompat$Builder;
System.err:     at com.telerik.localnotifications.Builder.build(Builder.java:59)
System.err:     at com.telerik.localnotifications.Builder.build(Builder.java:38)
System.err:     at com.telerik.localnotifications.NotificationAlarmReceiver.onReceive(NotificationAlarmReceiver.java:30)
System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3592)
System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:211)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7116)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.NotificationCompat$Builder"
on path: DexPathList[[zip file "/data/app/org.nativescript.notifications-Jp2k77OjxHG_RK2sfRtBjg==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.notifications-Jp2k77OjxHG_RK2sfRtBjg==/lib/x86, /data/app/org.nativescript.notifications-Jp2k77OjxHG_RK2sfRtBjg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 12 more

**Comment by EddyVerbruggen** [comment]
Are you using NativeScript 6 (RC)?

**Comment by jasenkabalac** [comment]
No, I think, I use 5.4.2 version

**Comment by Reached** [comment]
I get the same error using 5.4.0 :/

**Comment by EddyVerbruggen** [comment]
Exactly. The latest major plugin version is for NativeScript 6+. IIRC it’s in the readme as well.

**Comment by Reached** [comment]
Yea, I just realised this as well, sorry @EddyVerbruggen !

**Comment by vijaychhetry** [comment]
what is the fix for above issue ?
