### ISSUE TITLE
"notRequests" is null not an object on xcode 11 ios 13

### ISSUE THREAD

**Issue by mohdaliali7777** [EddyVerbruggen/nativescript-local-notifications#167]
ON xcode 11 the variable notRequests is null when there are no scheduled notifications, this causes the app to terminate when it reaches 
`for (let i = 0; i < notRequests.count; i++) {` line 343 on local-notifications.ios.js
Adding this code solved it for me
```
                        if (notRequests) {
                            for (var i = 0; i < notRequests.count; i++) {
                                scheduledIds_1.push(notRequests[i].identifier);
                            }
                        }
```

**Comment by EddyVerbruggen** [comment]
Thanks!
