### ISSUE TITLE
Triple notifications and no text

### ISSUE THREAD

**Issue by DeehSlash** [EddyVerbruggen/nativescript-local-notifications#171]
When I'm scheduling a notification to now, the system shows 3 notifications (instead of just one), and there's no text at all, you can see this in the screenshot below:

![Screenshot_20191021_025346](https://user-images.githubusercontent.com/15927886/67179928-5b1d0b80-f3ae-11e9-990c-5780a2ca7cf8.png)

I'm testing on an Android emulator running version 5.1.

My code:

```js
             LocalNotifications.schedule({
                  title: 'Alerta',
                  body: `Uma ocorrência de ${occurrence.category.name} foi registrada próxima ao seu local atual`,
                  bigTextStyle: true
                })
```
Already tried without bigTextStyle, but same thing.
PS: I'm using local notifications on a Background Service.

**Comment by DeehSlash** [comment]
This also happens on Android 9.

**Comment by DeehSlash** [comment]
Sample project: https://github.com/DeehSlash/nativescript-local-notifications-bug

**Comment by EddyVerbruggen** [comment]
Can you at least include the `at` property, so the plugin has an idea when to trigger it? I don't know if that helps, but I always do it (like in the demo apps) and don't have this problem.

**Comment by DeehSlash** [comment]
Already solved, see: https://stackoverflow.com/questions/58492792/plugin-nativescript-local-notifications-triplicates-the-notification-and-theres

As pointed by Manoj, I was passing an Object to the Schedule method, not an Array, so that was the problem.
