### ISSUE TITLE
Android is always returning true

### ISSUE THREAD

**Issue by ezlo-ionutrusu** [EddyVerbruggen/nativescript-local-notifications#173]
If u disable the notifications in settings it will not work anymore.
Propose modifying the local-notifications.android.js to 

LocalNotificationsImpl.prototype.hasPermission = function () {
        return new Promise(function (resolve, reject) {
            try {
**var context = utils.ad.getApplicationContext();
                const hasPermission=NotificationManagerCompatPackageName.NotificationManagerCompat.from(context).areNotificationsEnabled();
console.log(`hasPermission:${hasPermission}`);**
resolve(hasPermission);
            }
            catch (ex) {
                console.log("Error in LocalNotifications.hasPermission: " + ex);
                reject(ex);
            }
        });
    };

**Comment by EddyVerbruggen** [comment]
Fixed by #175
