### ISSUE TITLE
Can't enable by method requestPermission notifications on android.

### ISSUE THREAD

**Issue by ezlo-anatoliiv** [EddyVerbruggen/nativescript-local-notifications#177]
Can't enable by method requestPermission notifications on android.
It is returning always `true` even the notifications are disabled.

```
requestPermission() {
    return new Promise((resolve, reject) => {
      try {
          resolve(true)
      } catch (ex) {
        console.log("Error in LocalNotifications.requestPermission: " + ex);
        reject(ex);
      }
    });
  }
```

**Comment by EddyVerbruggen** [comment]
I don’t think you can actually request permission if the user disabled them manually. But what we could do is returning the result of “hasPermission” instead. Would that help?

**Comment by ezlo-anatoliiv** [comment]
You need is checking actual state for status of notifications and return true/false like it method works for iOS

**Comment by EddyVerbruggen** [comment]
Yes that’s what I proposed, except for the bit where you redirect the user to the settings. Did you find a good way to implement that?

**Comment by ezlo-anatoliiv** [comment]
Actually no, for now you can check only actual state for settings and return `true/false` like for iOS. It will fix current bug for this method.

**Comment by EddyVerbruggen** [comment]
Sure, let me fix that for you later today.

**Comment by ezlo-anatoliiv** [comment]
Thanks very much

**Comment by EddyVerbruggen** [comment]
Please update to 4.1.1.

**Comment by ezlo-anatoliiv** [comment]
Thanks
