### ISSUE TITLE
This notif as music player status. Help me

### ISSUE THREAD

**Issue by andipahlevy** [EddyVerbruggen/nativescript-local-notifications#194]
How to make the notification always showing?. i have add "ongoing" and set it to true but when i tap the notification body, the notification is gone. How to make this plugin works like mp3 player status?
Thanks

**Comment by coder-ashwin** [comment]
@andipahlevy there is a method called when the notification body is tapped, make the notification come again when it is tapped. It will look like the notification never removed.
