### ISSUE TITLE
Incorrect package.json and d.ts to use as node module.

### ISSUE THREAD

**Issue by xLama** [EddyVerbruggen/nativescript-local-notifications#25]
First. Thanks for this fantastic plugin.

I had problems to use it as node module when you install wirh npm install. 

To solve it:

Open node_modules/nativescript-local-notifications/local-package.json and add 
"typings": "local-notifications.d.ts" as new object property.

Later, go to local-notifications.d.ts  and remove declare module "nativescript-local-notifications" {}
Remove module declaration, not members inside it.

Now you can use it wrtiting, for example:

import {schedule} from "nativescript-local-notifications"

without import d.ts as reference

**Comment by EddyVerbruggen** [comment]
Hi,

Thanks for the pointers, I'll change that. I've already changed this for a few other plugins but going through all of them takes time :)

👍

**Comment by EddyVerbruggen** [comment]
Published with 1.1.7 on npm
