### ISSUE TITLE
Custom notification sound!

### ISSUE THREAD

**Issue by jmoleiro** [EddyVerbruggen/nativescript-local-notifications#3]
Great work. Would be great to have custom notification sounds :)

**Comment by kayrules** [comment]
yup, definitely +1 for this feature. ;)

**Comment by mikeres0** [comment]
+1 :+1:

**Comment by Obsessive** [comment]
This feature has been implemented on our repository [here](https://github.com/Obsessive/nativescript-custom-local-notifications) .
How about we merge the two?

**Comment by EddyVerbruggen** [comment]
@Obsessive Yeah that would be great, can you send a PR to this repo perhaps?
