### ISSUE TITLE
ios simulator throws local-notifications.js:26:37: JS ERROR ReferenceError: Can't find variable: Notification

### ISSUE THREAD

**Issue by greenstevester** [EddyVerbruggen/nativescript-local-notifications#34]
Hi There,

When running with the ios simulator the following exception is thrown:

`file:///app/tns_modules/nativescript-local-notifications/local-notifications.js:26:37: JS ERROR ReferenceError: Can't find variable: Notification`

I tested to see if it worked on my iphone and it does with no issues.

my setup:
----------
Simulator: Version 9.3 (SimulatorApp-645.9)

 "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "lodash": "^4.16.6",
    "nativescript-angular": "1.2.0",
    "nativescript-intl": "~0.0.8",
    "nativescript-local-notifications": "^1.2.0",
    "punycode": "1.3.2",
    "querystring": "0.2.0",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": ">=2.5.0 || >=2.5.0-2016",
    "url": "0.10.3"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.2",
    "@types/lodash": "^4.14.37",
    "typescript": "~2.0.3",
    "zone.js": "^0.6.21"
  }

**Comment by sorakthunly** [comment]
Can confirm. I'm currently facing the same issue. The app just exits when launched.

**Comment by EddyVerbruggen** [comment]
Which command do you use to run the app? Have you tried without livesync?

**Comment by sorakthunly** [comment]
I rebuilt and redeployed the app. It now works well. :D

**Comment by EddyVerbruggen** [comment]
Cool. Most of the times issues like this are caused by using livesync without ever doing a regular `tns run ..`. And if that doesn't help removing and readding the platforms is a solid solution. If those don't help I'm happy to take a look.
