### ISSUE TITLE
How to disabled notification sound

### ISSUE THREAD

**Issue by manishmlv50** [EddyVerbruggen/nativescript-local-notifications#35]
How do i disabled sound, but still receive notifications

LocalNotifications.schedule([{
        id: message.entityId,
        title: message.title,
        body: message.body,
        smallIcon: 'res://icon',
        largeIcon: 'res://icon'
      }]).then(() => {
            console.log("Notification Scheduled");
          },(error)=> {
            console.log("doScheduleId5 error: " + error);
          }
      );

Thank you

**Comment by EddyVerbruggen** [comment]
Didn't [this](https://github.com/EddyVerbruggen/nativescript-local-notifications#schedule) help you? Look for `sound`.

**Comment by EddyVerbruggen** [comment]
Set sound to `null`.

**Comment by benedictstrube** [comment]
Setting sound to `null` does not disable it on Android for me. Is disabling the sound also iOS only as setting it to a custom sound is?
