### ISSUE TITLE
Fix package.json to supporting AoT compilation

### ISSUE THREAD

**Issue by newapx** [EddyVerbruggen/nativescript-local-notifications#36]
I try use webpack and after command `npm run start-android-bundle` got the error: not find module `nativescript-local-notifications`.

For correct compilation I replace in `package.json` property `main`
from `"main": "local-notifications.js",` to `"main": "local-notifications",`

More info: https://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#recommendations-for-plugin-authors

**Comment by EddyVerbruggen** [comment]
Yeah I know, I'll do that now..
