### ISSUE TITLE
Angular nativescript - android

### ISSUE THREAD

**Issue by 4zriel** [EddyVerbruggen/nativescript-local-notifications#38]
Hi,

It is a way to use it with angular? I've tried to define it in main.ts file, in one in my compontent and event if LocalNotification as a module works fine (I can schedule a notification, get ids of already scheduled etc) but in any case I can`t get application after closing my app :/

**Comment by EddyVerbruggen** [comment]
Do you have a sample project I can clone?

**Comment by 4zriel** [comment]
@EddyVerbruggen  Sure one moment and I will make it public - it is just a simple todo app with firebase but it is my start with nativescript :)
https://github.com/4zriel/TodoAppAndroid

**Comment by EddyVerbruggen** [comment]
What did you actually mean by "I can`t get application after closing my app"?

**Comment by 4zriel** [comment]
*Notification - I can't get any notification when I closing my app

**Comment by EddyVerbruggen** [comment]
Ah ok.. that shouldn't be related to Angular at all. But work a look at your project nonetheless.

If anyone has notifications working on Android and want to take a look: be my guest :)

**Comment by rijine** [comment]
@EddyVerbruggen will it work if we close application? kind of service?

**Comment by EddyVerbruggen** [comment]
That's the idea yeah.

**Comment by EddyVerbruggen** [comment]
For anyone looking for Angular guidance, please check out [this repo](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/tree/master/app/feedback).
