### ISSUE TITLE
Stopped working after upgrade to xcode 8.2 

### ISSUE THREAD

**Issue by devna13** [EddyVerbruggen/nativescript-local-notifications#42]
I upgraded to xcode 8.2 and pods 1.2.0, and now the app crashes when calling;

```
		LocalNotifications.requestPermission();

Feb 23 12:47:14 com.apple.CoreSimulator.SimDevice.D77BFD9C-7748-4857-9A08-4F8F4F0D8838.launchd_sim[81199] (UIKitApplication:com.xyz.test[0x2be6][84445]): Service exited due to Segmentation fault: 11

```
Thanks

**Comment by EddyVerbruggen** [comment]
That's not a helpful error I'm afraid.

Did you already remove and re-add the iOS platform?

**Comment by devna13** [comment]
yes I tried that.... 

I just made a code change and added a then callback and now its working! 

	LocalNotifications.requestPermission().then(
			function (granted) {
				console.log("Permission granted? " + granted);
			});

Thanks anyways.
