### ISSUE TITLE
Android foreground/background check

### ISSUE THREAD

**Issue by jumpinggoofballs** [EddyVerbruggen/nativescript-local-notifications#46]
Hello,

Thank you very much for the work on this!

I have the feeling that this is going to be an incredibly n00bish question but here goes:

I am having some trouble getting notifications to trigger/not trigger depending on what page is active in a chat app. So far, I have managed to respond to whether I am on the correct page in the app, but not also if the app is in the foreground or background. How can I also check that?

Code: 

> // if the notifications is from the user currently represented in the chat view, just update the chat view via the newMessageReceived event on that page
    if (frameModule.topmost().currentEntry.context.chatRef === messageSenderId) {
        frameModule.topmost().currentPage.notify({
            eventName: 'newMessageReceived',
            object: this
        });
    } else {
        // schedule notification
        LocalNotifications.schedule([{
            id: randomNotificationId,
            title: 'App Title',
            body: 'You have a new message from ' + messageSender
        }]).then(() => {
            notificationListenerInit(messageSenderId);
        }, error => {
            console.log('error');
        });
    }

The conditional here works fine except for when the app is in the background AND the active page is still the one for this chat partner. Obviously the notification should always trigger while the app is in the background, but how do I do that?

**Comment by EddyVerbruggen** [comment]
Plugin version 3.0.0 adds a `foreground` boolean flag to the notification (which you get in the callback you set via `addOnMessageReceivedCallback`).
