### ISSUE TITLE
Typescript + Angular support and Demo

### ISSUE THREAD

**Issue by rijine** [EddyVerbruggen/nativescript-local-notifications#47]

**Comment by EddyVerbruggen** [comment]
Is there a question here, or are you creating those things?

**Comment by rijine** [comment]
I'm looking for some sample with typescript and angular.

**Comment by EddyVerbruggen** [comment]
It's just like any other plugin I guess. Here's something to get you started: https://github.com/EddyVerbruggen/nativescript-local-notifications#typescript-support

Angular isn't an issue here as there's no UI definition involved.
