### ISSUE TITLE
Notification show with small delay

### ISSUE THREAD

**Issue by surdu** [EddyVerbruggen/nativescript-local-notifications#55]
First of all, thank you very much for your work!

My problem is not very crucial, but I think that it is something that can be improved.

When I schedule a notification for 'now' (the default) the notification takes a while to show, usually about 2 - 3 seconds.

**Comment by surdu** [comment]
Maybe for "now" notification `notificationManager.notify()` could be used instead of the `alarmManager.set()` ?

**Comment by EddyVerbruggen** [comment]
I never intended this plugin to be used for immediate feedback, but that may be a nice addition.

**Comment by surdu** [comment]
I have already code for this. I will have to see how/if it translates to iOS, clean it up a bit, and I will make a PR.

**Comment by EddyVerbruggen** [comment]
Sounds great!

**Comment by evnds** [comment]
I also with this problem
No default solution yet.

**Comment by surdu** [comment]
Made a PR. Only for Android, at least for now. I didn't have the time to look if for ios this is an issue and/or if there is a solution for it.
