### ISSUE TITLE
Update notification title/body

### ISSUE THREAD

**Issue by surdu** [EddyVerbruggen/nativescript-local-notifications#56]
As far as I can tell, there is no way to retrieve a notification after it is scheduled in order to update it.

A scenario where one would want to do that is for ongoing notifications like "Downloading... 20%"

**Comment by EddyVerbruggen** [comment]
Please point me to the spec of the native SDK where it's explained how to do that. 

AFAIK that's not allowed.

**Comment by surdu** [comment]
If you keep a reference to the [Notification.Builder](https://developer.android.com/reference/android/app/Notification.Builder.html) you can call [setContentText](https://developer.android.com/reference/android/app/Notification.Builder.html#setContentText(java.lang.CharSequence)) to update the notification body.

I would imagine is the same with the [NotificationCompat.Builder](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html) that you are using.

**Comment by surdu** [comment]
My bad. I missed the fac I was re-calling .build() after each change :(

Sorry
