### ISSUE TITLE
users notifications

### ISSUE THREAD

**Issue by nelsonwilliam11** [EddyVerbruggen/nativescript-local-notifications#57]
i know this not the right place for this issue but i really need to know how to make users notifications 
  like if someone liked your post it notify you about that or if someone started following you etc
how can i implement that 
thanks

**Comment by davorpeic** [comment]
It looks like you need Push notifications sent by your backend handling those likes/follows etc.

**Comment by nelsonwilliam11** [comment]
Yes that's what am.looking for
