### ISSUE TITLE
Submitted app returned for errors – Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by ickata** [EddyVerbruggen/nativescript-local-notifications#59]
Hi @EddyVerbruggen ,

I got my app returned after uploading it to App Store with the following message:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "XXXXX". To process your delivery, the following issues must be corrected:
> 
> Unexpected CFBundleExecutable Key - The bundle at '/Payload/mobile.app/app/tns_modules/nativescript-local-notifications/native-src/ios/LocalNotificationsPlugin/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.
> 
> Unexpected CFBundleExecutable Key - The bundle at '/Payload/mobile.app/app/tns_modules/nativescript-local-notifications/native-src/ios/LocalNotificationsPluginTests/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

Can you please advise?

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this.

This is the first time an issue like this popped up in any of my repos, even in repos that have an embedded native iOS library like this one has... so I'm not entirely sure if it's the plugin's fault or something in your build messing it up, but I've changed a few bits and hope version 1.2.2 will solve it for you.

The second part of Apple's rejection should be gone for sure (as I removed the empty Tests folder), but the first part I'm not sure of... it looks like the framework is created per Apple's guidelines and I can't find anything wrong with it.

Can you make sure you remove and re-add the iOS platform folder after updating this plugin?

**Comment by ickata** [comment]
Hi Eddy,

I confirm that with the new plugin release my build passed processing.
