### ISSUE TITLE
Set Icon and kill already send notifications

### ISSUE THREAD

**Issue by nicHoch** [EddyVerbruggen/nativescript-local-notifications#6]
Hi.
Thanks for the good plugin.

I wounder if it is possible to set the Icon that is uses in the notification manually?
And it would by nice to kill an already send notification - so it can by used as some kind of status update. 

Nicky

**Comment by EddyVerbruggen** [comment]
I'm not sure how `kill` would be different from `cancel`?

**Comment by EddyVerbruggen** [comment]
Just released 1.1.1 with `smallIcon` and `largeIcon` properties. Check the readme for details.
