### ISSUE TITLE
BigTextStyle for Android

### ISSUE THREAD

**Issue by nikolayczyk** [EddyVerbruggen/nativescript-local-notifications#62]
Hey @EddyVerbruggen,
I want to show multiline message in Notifications.
There is already an entry on stackoverflow on this topic.
Link: 
[https://stackoverflow.com/questions/45666384/firebase-push-notification-how-to-show-multiline-message-in-notification](url)
I have extended your plugin therefore. I added the BigTextStyle as a style for Android. 
Could you give me the permission to push my adjustments into the master?
I have already tested my adjustments. I've already pushed the adjustments in my fork.
I would like to share my adjustments.

Here are my changes:
_local-notifications-common.js_

`LocalNotifications.defaults = {`
`  id: 0,`
`  title: '',`
`  body: '',`
`  badge: 0,`
`  interval: 0,`
`  ongoing: false,`
`  groupSummary:null,`
`  bigTextStyle: false`
`};`

_local-notifications.d.ts_

`export interface ScheduleOptions {`
` ...`
`        bigTextStyle?: boolean;`

_local-notifications.android.js_

`LocalNotifications.schedule = function (arg) {`
` ...`
        `if(options.bigTextStyle){`
          `var bigTextStyle = new android.support.v4.app.NotificationCompat.BigTextStyle();`
          `bigTextStyle.setBigContentTitle(options.title);`
         `bigTextStyle.bigText(options.body);`
          `builder.setStyle(bigTextStyle);`
        `}`

Best regards
Tim

**Comment by EddyVerbruggen** [comment]
Hi Tim, did you open a PR to this repo? I think it would make a great addition!

**Comment by nikolayczyk** [comment]
I created a new branch (BigTextStyle).
But when I try to push I get a error message.

_remote: Permission to EddyVerbruggen/nativescript-local-notifications.git denied to nikolayczyk.
fatal: unable to access 'https://github.com/EddyVerbruggen/nativescript-local-notifications.git/': The requested URL returned error: 403_

**Comment by nikolayczyk** [comment]
I have opened a PR. Sorry but I have not used Github often.

**Comment by EddyVerbruggen** [comment]
Thank you! First time for everything, right? :)

**Comment by EddyVerbruggen** [comment]
Great work, part of 2.0.0! 👌🏻
