### ISSUE TITLE
Restarts App even when it is running

### ISSUE THREAD

**Issue by fabioloreggian** [EddyVerbruggen/nativescript-local-notifications#65]
[Angular]

When I click on a notification when the app is in the foreground or even background, it restarts the application losing all previous state. 

I see it prints this when the app 'restarts':
`JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.`

Is this intended?

**Comment by fabioloreggian** [comment]
I also know it restarts my app, because the constructor to a service (@Injectable) gets called again, which shouldn't happen

**Comment by EddyVerbruggen** [comment]
My be related to the `launchMode` in your `AndroidManifest.xml`.. nothing the plugin can do about that.

**Comment by fabioloreggian** [comment]
Thank you, Ill have a look at that now

**Comment by fabioloreggian** [comment]
Add `android:launchMode="singleTask"` to your app's activity section. This tells the Android operating system to launch the app with a new instance of the activity, or use an existing one. Without this your app will launch multiple instances of itself which is no good.

This worked

**Comment by EddyVerbruggen** [comment]
👍
