### ISSUE TITLE
Issue with schedule function

### ISSUE THREAD

**Issue by Lingfar** [EddyVerbruggen/nativescript-local-notifications#66]
Hello, 

I'm trying to use this plugin but I have a problem with the schedule function.
I get the following error when I try do schedule any notification :
_JS: Error in LocalNotifications.schedule: TypeError: notificationManager.getNotificationChannel is not a function_

I downloaded your demo app https://github.com/EddyVerbruggen/nativescript-local-notifications-demo and I still got the same error.

I'm using a Nexus 5X with Android 8.0.0.

**Comment by ShawnPavel** [comment]
I can confirm this issue on a Google Pixel 2 with Android 8.0.0.

**Comment by gregersen79** [comment]
Can also confirm this on Google Pixel 2 with Android 8

**Comment by sm1ddy** [comment]
Yeah I have a similar issue on Android 8.0.0, when trying to schedule a notification I get:
"Error in LocalNotifications.schedule: TypeError: builder.setChannelId is not a function"

I'm running an up to date sdk as well.

**Comment by nmandyam** [comment]
It's baaack! I get this when I try LocalNotifications.schedule...:

> TypeError:
>  notificationManager.getNotificationChannel is not a function
>     at file:///.../files/app/tns_modules/nativescript-local-notifications/local-notifications.js:105:57
>     at Object.LocalNotifications.schedule (file:///.../files/app/tns_modules/nativescript-local-notifications/local-notifications.js:25:10)

I replaced the include.gradle with the new code from [here](https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/dafbf22a6fb848f95a6777f28d984456b773c72e/platforms/android/include.gradle), but that's made no difference.

The plugin is current - "nativescript-local-notifications": "^2.0.2".

My device is a Motorola X4 with Android 8.0.0.

**Comment by SSipplAIT** [comment]
Did you find a solution for this issue? I am confronted with the same error message.

**Comment by EddyVerbruggen** [comment]
Beats me.. that method is [supposed to be available in API level 26](https://developer.android.com/reference/android/app/NotificationManager.html#getNotificationChannel(java.lang.String)) and works fine on my Android 8 device (just tested it with [the demo app](https://github.com/EddyVerbruggen/nativescript-local-notifications-demo)).

**Comment by nmandyam** [comment]
I updated the platform to 3.4.2, following the experience of radu2501 [here](https://github.com/EddyVerbruggen/nativescript-local-notifications/issues/75), but that's made no difference on my x4. 
Any thoughts?

**Comment by stevegardnersa** [comment]
I had this same problem and just went into Android Studio and made sure I had all the SDKs and Build-Tools updated and then it started working.
