### ISSUE TITLE
New option to set the priority/importance of the notification.

### ISSUE THREAD

**Issue by kirtontt** [EddyVerbruggen/nativescript-local-notifications#69]
First of all GREAT WORK with this plugin. This is a more of a request than an issue.
Would it be possible to add a new option to allow us to set the importance of the notification? I would like to be able to use the Heads-up notification in android as seen in the following link: https://stackoverflow.com/questions/29949501/android-show-notification-with-a-popup-on-top-of-any-application/38040216

**Comment by EddyVerbruggen** [comment]
Thanks for the request. I've done a major rewrite of this plugin, and with version 3.0.0 you can now set `forceShowWhenInForeground` to `true`. Works on both iOS and Android.
