### ISSUE TITLE
Plugin not working after tns-core-modules update

### ISSUE THREAD

**Issue by hdrdiab** [EddyVerbruggen/nativescript-local-notifications#73]
After updating the `tns-core-modules` to `3.4.0` the schedule function fails and emits an error when called.Here is the error:
`JS: Error in LocalNotifications.schedule: TypeError: Cannot read property 'NotificationClickedActivity' of undefined
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'NotificationClickedActivity' of undefined
JS: TypeError: Cannot read property 'NotificationClickedActivity' of undefined`

To replicate the error create a new project using `tns create --ng newProj` , add the plugin and try using the schedule function, an error similar to the error above would appear.
Note that i made the plugin work again by downgrading the core modules to 3.3.0 , tns-android to 3.3.1,and tns-ios to 3.3.0

**Comment by shabib3** [comment]
Same issue here

**Comment by EddyVerbruggen** [comment]
Looks like with NativeScript 3.4 plugins can no longer just drop .jar files in a libs folder.. so I wrapped the native plugin code in an .aar and now it's working again. Available with 2.0.2 from npm.
