### ISSUE TITLE
Error in LocalNotifications.schedule: TypeError: Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by VanVangog** [EddyVerbruggen/nativescript-local-notifications#75]
In my app i'am try this code

var LocalNotifications = require("nativescript-local-notifications");
LocalNotifications.schedule([{
    id: 1,
    title: 'The title',
    body: 'Recurs every minute until cancelled',
    at: new Date(new Date().getTime() + (10 * 1000)) // 10 seconds from now
  }]).then(
      function() {
        console.log("Notification scheduled");
      },
      function(error) {
        console.log("scheduling error: " + error);
      }
  )
In home-view-model.js but i have issue "Error in LocalNotifications.schedule: TypeError: Cannot read property 'class' of undefined".
What can be wrong?

**Comment by radu2501** [comment]
I had the same issue and I fixed it by running `tns platform remove android && tns run android`.

**Comment by VanVangog** [comment]
thx it's work

**Comment by Dorgam** [comment]
yup @radu2501 solution fixes it, thanks :)
