### ISSUE TITLE
getScheduledIds() returns ids of notifications that have already been published

### ISSUE THREAD

**Issue by resnickj** [EddyVerbruggen/nativescript-local-notifications#77]
I notice that if I schedule a notification with e.g. ID=101 to be shown in e.g. 10 seconds, and then wait 10 seconds, the notification is shown as expected. However, calling getScheduledIds() continues to return the ID 101 in it's list, unless I explicitly cancel it. Is this by design? I would have thought that once the time elapses and the notification is shown, it is no longer considered "scheduled" and therefore would not be returned by getScheduledIds(), but perhaps I'm misunderstanding something ...

**Comment by EddyVerbruggen** [comment]
Looking at the code, this must be on Android.

Those id's are currently not cleared unless you [cancel them programmatically ](https://github.com/EddyVerbruggen/nativescript-local-notifications#cancel). That's a bug.

**Comment by EddyVerbruggen** [comment]
Should be good now, thanks for reporting!
