### ISSUE TITLE
Not compiling in {N} 1.7.1

### ISSUE THREAD

**Issue by Milewski** [EddyVerbruggen/nativescript-local-notifications#8]
I am having a hard time trying to compile.. it is always throwing errors...

```
:mergeNativescript-geolocationNativescript-local-notificationsNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugResources FAILED
```

**Comment by EddyVerbruggen** [comment]
That should be gone because of [this commit](https://github.com/EddyVerbruggen/nativescript-local-notifications/commit/269b29e8a00bfcf64fe2ef1a1a8cf9558f75a025) I did yesterday.. can you remove your android platform, update the plugin and re-add the android platform?

**Comment by Milewski** [comment]
its compiling now.. however it looks like there is conflict with 
```
"nativescript-push-notifications": "^0.0.15"
```
whenever i include the push notification.. the local stop working..
