### ISSUE TITLE
Setting an Exception feature

### ISSUE THREAD

**Issue by joey0xx** [EddyVerbruggen/nativescript-local-notifications#80]
Currently the user can schedule a notification and it will notify the user without fail depending on how the user configures the occurrence (daily, weekly,monthly etc). But it would be nice if there was a way to add exceptions (skip a notification at certain hours).

**Comment by EddyVerbruggen** [comment]
Then I guess you'll have to schedule it like that. I mean, schedule multiple notifications with interval "day" and trigger those at the hour-of-day that you please.
