### ISSUE TITLE
Sometimes local notifications are scheduled but doesn't show up in the notification center

### ISSUE THREAD

**Issue by erkanarslan** [EddyVerbruggen/nativescript-local-notifications#81]
I use `nativescript-plugin-firebase` to get notifications from server. I get them as data only messages and create a notification in the device with this plugin. The problem is sometimes I see the notifications but usually they don't show up in the notification center.

To debug this problem I am logging activities in a file when I get messages from FCM. Server sends the messages, application receives them and immediately schedules the local notification (success callback is called) but it doesn't show up.

This looks like a random behavior. I thought maybe app is going idle and doesn't create notifications but even when I open the app, put it to background and receive a message a few seconds after that I still don't see a notification.

One thing I noticed is that after some time app starts to show notifications. Every message I send after that is shown in the mobile device but after some time it will stop showing them. This cycle repeats but it seems like there is no fixed duration or time for that.

Problem happens on both iOS and Android.

**Comment by EddyVerbruggen** [comment]
I have no idea what this is about, but it may well be fixed with plugin version 3.0.0. Please reopen with a repo and steps if not.
