### ISSUE TITLE
Actions in notification

### ISSUE THREAD

**Issue by krisidmisso** [EddyVerbruggen/nativescript-local-notifications#86]
Is there any option to setup actions like this?
![image](https://user-images.githubusercontent.com/9657055/40365827-d122d316-5dd5-11e8-847f-72f75ccaaf1f.png) (ACCEPT - REJECT buttons)

**Comment by EddyVerbruggen** [comment]
Not at the moment.

**Comment by EddyVerbruggen** [comment]
See #95.
