### ISSUE TITLE
Show notifications when app is in the foreground?

### ISSUE THREAD

**Issue by NL33** [EddyVerbruggen/nativescript-local-notifications#87]
This plugin is great. The limit I find is that the notification does not show if the app is still open on the phone. 

This is especially a problem because if 1) a user sets a notification, and then 2) locks their phone (so the app no longer shows, but the user would expect to see a notification), the notification does NOT show, because the system still thinks the app is open.

This is an enhancement request: can the plugin allow notifications to be shown if the app is open in the foreground?

In iOS, there appears to be some discussion of how to do this with Swift/ Obj-C: https://stackoverflow.com/questions/30852870/displaying-a-stock-ios-notification-banner-when-your-app-is-open-and-in-the-fore. 

It would be very helpful if this was possible by using the plugin without having to delve into Swift/Obj C programming.

**Comment by EddyVerbruggen** [comment]
This depends on #95 because `UNUserNotificationCenter` will be required for iOS.

**Comment by NL33** [comment]
This would be really helpful.
