### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by Lev09** [EddyVerbruggen/nativescript-local-notifications#9]
I am trying to use this plugin with NativeScript 2 and typescript but I got error telling that the module is not found

**Comment by EddyVerbruggen** [comment]
Can you try the [demo app](https://github.com/EddyVerbruggen/nativescript-local-notifications-demo) first and see if that works for you?

Also, this is way too little info to even remotely start guessing what's going wrong on your end.

**Comment by Lev09** [comment]
@EddyVerbruggen The demo app is working.
But in my project I can't import this package  using `import` statement.

**Comment by EddyVerbruggen** [comment]
You'll have to figure that out yourself if you don't share your code. But please make an effort to compare the demo app with yours first.

**Comment by Lev09** [comment]
Is there any type definition(.d.ts) for TypeScript ?

**Comment by EddyVerbruggen** [comment]
It's in the root folder of this repo..

**Comment by iagocaldeira** [comment]
I have the same issue using
`import {LocalNotifications} from "nativescript-local-notifications/local-notifications";`

**Comment by EddyVerbruggen** [comment]
I've added a [little chapter on TypeScript support](https://github.com/EddyVerbruggen/nativescript-local-notifications#typescript-support) to the README. Hope that helps!
