### ISSUE TITLE
notification callback without tapping

### ISSUE THREAD

**Issue by des-esseintes** [EddyVerbruggen/nativescript-local-notifications#90]
hello
thank you for your effort, the plugin is very useful (not the first time im telling you this hehe)
just wondering, if it's possible to trigger an event inside the app even without tapping the notification?
currently im trying to set up an app with alarms and would like it to refresh when an event occurs. not sure if its possible, but worth asking anyway. thanks :)

**Comment by EddyVerbruggen** [comment]
Unfortunately, that's not something the native APIs allow.

**Comment by des-esseintes** [comment]
yes, Eddy, i shoud've closed the issue myself already, solved the task w/ a different approach, thank you!
