### ISSUE TITLE
Feature request: Let the app developer customise the channel name

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-local-notifications#92]
https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/ea34422624116877b1db13693b1c60d597572099/native-src/android/app/src/main/java/com/telerik/localnotifications/NotificationRestoreReceiver.java#L74

Hi Eddy,
In its current state, when you long press a notification created by this plugin on android,
it says "myChannelName"
It would be nice if you let the app developer customize that name.
![notification](https://user-images.githubusercontent.com/9407019/41509293-3aef8638-726f-11e8-8e3f-508a2c4b3ef7.jpeg)

**Comment by EddyVerbruggen** [comment]
I have *never* longpressed a notification actually. Thanks for educating me!

Version 2.0.4 has a `channel` property which you can pass in.

**Comment by Erudition** [comment]
It's more than just a decoration! It determines the properties of the notification, like the sound and priority - all of which can be changed by the user on a per-channel basis.
