### ISSUE TITLE
cancelAll() doesn't cancel notifications that are already open

### ISSUE THREAD

**Issue by atheros** [EddyVerbruggen/nativescript-local-notifications#97]
```typescript
import { Component } from "@angular/core";

import * as LocalNotifications from 'nativescript-local-notifications';
import * as moment from 'moment';

@Component({
    selector: "ns-items",
    moduleId: module.id,
    template: `
        <ActionBar title="My App" class="action-bar">
        </ActionBar>

        <StackLayout class="page">
            <Button text="Show notification" (tap)="onShowNotification()"></Button>
            <Button text="Cancel 1" (tap)="onCancel1()"></Button>
            <Button text="Cancel All" (tap)="onCancelAll()"></Button>
        </StackLayout>
`
})
export class ItemsComponent {
    constructor() { }

    onShowNotification() {
        LocalNotifications.schedule([{
            id: 1,
            title: 'Scheduled notification',
            body: 'Interesting, no?'
        }]);
    }

    onCancel1() {
        LocalNotifications.cancel(1);
    }

    onCancelAll() {
        LocalNotifications.cancelAll();
    }
}
```
In the above code I open a notification with onShowNotification(). The notification get's opened.
Calling onCancelAll doesn't do anything. Calling onCancel1() cancels that notification

**Comment by EddyVerbruggen** [comment]
Do you see this on iOS, Android, or both?

**Comment by atheros** [comment]
@EddyVerbruggen on Android, I didn't check on iOS

**Comment by EddyVerbruggen** [comment]
The `cancel` functions are meant for removing a scheduled item, not for hiding an already shown notification. The fact that it may dismiss an already open notification is more of a side effect than a feature.

**Comment by atheros** [comment]
I am not sure about it. I didn't find any documentation suggesting that cancelAll() should drop visible notifications or explicitly that is should keep them.

However I saw apps that had multiple active notifications, clicking on one would open the app and all other notifications would disappear.

**Comment by EddyVerbruggen** [comment]
I believe this has been 'fixed' (or at least the behaviour changed) with plugin version 3.0.0.
